version: '2'

services:

  sonardb:
    image: postgres:9.5
    container_name: sonardb
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data

  sonar:
    image: sonarqube:6.0
    container_name: sonar
    restart: always
    ports:
      - "9000:9000"
      - "5432:5432"
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar

  nexus:
    image: sonatype/nexus3:3.0.0
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /opt/nexus/:/nexus-data

  jenkins:
    image: jenkins:2.7.2
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /opt/jenkins/:/var/jenkins_home
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432 
    depends_on:
      - nexus
      - sonar

